#!/bin/sh

DELAY=1
if [ "$#" -eq 1 ]
then
  DELAY=$1
fi

COUNTER=0

while [ ! -f /shared/shutdown.txt ]
do
    NOW=$(date +%s)
    COUNTER=$((COUNTER+1))

    echo STEP $COUNTER $NOW 
    #core-cli -js query session -i 1 | jq -r '.session.nodes[] | select(.dir) | [.name, .position.x, .position.y ] | @csv'
    position_dump
    echo
    sleep $DELAY
done